spring:
  datasource:
    url: jdbc:h2:mem:~/jwt
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 359784327303-3h2389h42ge33v990iubk4aqck3mj2o3.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          naver:
            client-id: TtU2HpfKx8m4A_JJhD_r
            client-secret: hnRAj89vff
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri : http://localhost:8080/login/oauth2/code/naver
          kakao:
            client-id: 55d6f3e6d86d66049f210faad338113f
            client-secret: DzTWAOL22KXwKyZiaecjivShsBnQxSL7
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
